
with open('analogical_circuit_paper.md', encoding='utf-8') as f:
    content = f.read()

MARKER = ('**[Claude Code \u2014 write mechanistic narrative here]**\n\n'
          '> *Using both the circuit walkthrough table AND the causal paths above*\n'
          '> *(including the figure), narrate the complete mechanistic story:*\n'
          '> *what did the model detect at each stage, how did signals travel*\n'
          '> *through the edges, which path was dominant, and why did the winner*\n'
          '> *beat the alternatives. Follow the style from the first prompt.*')

count = content.count(MARKER)
print(f'Markers found: {count}')

narratives = [
"""**[EARLY]** For "Fish is to water as bird is to," the early-layer features engage primarily with structural and syntactic parsing. The top early node, F9865 at Layer 6 (node_id=6_9865_3, inf=0.7997), is labeled "code and file paths" -- a structural-register feature that fires on the formal pattern of the analogy template. F2866 at Layer 4 (node_id=4_2866_2, inf=0.7989) detects "the word 'is'" -- the model is explicitly tracking the relational connector. F9088 at Layer 2 (node_id=2_9088_3, inf=0.7985) activates for "things which are believed, demonstrated, or thought to be true," reflecting the declarative, definitional nature of analogy frames. Crucially absent are any domain-specific features for fish, water, or birds -- the early circuit is operating almost entirely on the syntactic structure of the analogy.

**[MIDDLE]** The middle layers show no explicit habitat/environment features. F13919 at Layer 7 (node_id=7_13919_8, inf=0.7995) fires for "words related to regulations, standards, and procedures" -- another structural-formalism feature. F8857 at Layer 9 (node_id=9_8857_5, inf=0.7993) detects "answer choices in mathematical questions," and F8494 at Layer 8 fires for "food, especially meat." These labels are unexpected for a habitat analogy -- they suggest the model's internal circuit for analogical reasoning uses features that generalize across many formal-comparison contexts rather than encoding domain-specific knowledge.

**[LATE]** The most interesting late-layer finding: F22 at Layer 0 (node_id=0_22_5, inf=0.8000) -- labeled "words ending in the suffix '-ality' or the word 'other'" -- achieves the highest influence score. This may reflect the model's encoding of the open-completion slot ("is to ___") as an abstract category placeholder. F14321 at Layer 14 (node_id=14_14321_8, inf=0.7999) fires for "words commonly found at the beginning of sentences or phrases," suggesting it is tracking the output-initiation context. F881 at Layer 21 (node_id=21_881_8, inf=0.7968) detects "connectives and technical terms."

**[TOKEN COMPETITION]** The model predicted " air" with only 11.7% probability -- the lowest confidence of all 10 prompts. The dominant excitatory path (Path 1, weight=60.8) is remarkably short: embedding -> L22/F9139927 -> LOGIT with edge weights 12.06 and 5.04. This 2-hop path bypasses all the labeled features entirely, suggesting that for this ambiguous analogy, the final token decision was driven by a direct embedding-to-late-layer route rather than the full multi-layer causal chain seen in high-confidence predictions.

**[SYNTHESIS]** This is the most ambiguous circuit in the dataset. The model has no strong domain-specific features for "air" or "sky" -- both are valid completions. The circuit is operating in a near-pure structural mode: the analogy template is recognized (structural features at L2-L6), the comparison slot is registered (F22 as abstract placeholder), and the logit is driven by a 2-hop excitatory path from an embedding feature. The 11.7% confidence reflects genuine competition: "sky," "air," and other habitat words have roughly equal support from the circuit, and the final choice of " air" appears to be driven by subtle token-level frequency biases rather than a strong domain-specific causal chain.""",

"""**[EARLY]** For "Puppy is to dog as kitten is to," the early layers immediately register the life-stage relational structure. The top early feature, F11438 at Layer 1 (node_id=1_11438_5, inf=0.8000), is labeled "the word 'as', and in some contexts words related to government or organization" -- the model locks onto the "as" connective that bridges the two analogy pairs, the structural heart of the A:B::C:? template. F12148 at Layer 1 (node_id=1_12148_6, inf=0.7997) fires for "words related to hosts, pathogens, and infections," and F5267 at Layer 3 (node_id=3_5267_4, inf=0.7995) for "words related to science and engineering that are nouns." These labels are surprising for an animal life-stage analogy but suggest the model uses a broad "category-member" feature cluster that spans biological taxonomy and scientific classification contexts.

**[MIDDLE]** The key middle-layer feature is F2909 at Layer 9 (node_id=9_2909_7, inf=0.7999), labeled "formulas, ratios, and mathematical notation." This recurring feature (also seen in the Cairo/Kenya graph) is the circuit's representation of the proportional/ratio structure of analogy -- "puppy:dog = kitten:cat" as a formal equivalence. F10565 at Layer 10 (label: "commonly used sayings or idioms") may be responding to the idiomatic quality of the analogy template. F4256 at Layer 14 activates for "a group of words including 'astronomy' and related terms" -- likely a general category-membership feature.

**[LATE]** F553 at Layer 25 (node_id=25_553_8, inf=0.7969) fires for "text passages written in all capital letters" -- an unusual late-layer feature that may be capturing the categorical salience of the answer. F6905 at Layer 23 (node_id=23_6905_8, inf=0.7961) fires for "nouns preceded by articles or adjectives within a specific context," which accurately describes the syntactic slot being filled.

**[TOKEN COMPETITION]** " cat" was predicted with 75.6% probability -- the second-highest confidence in the dataset after Germany (97.3%). The dominant path is Path 1 (mixed, weight=551.7), which begins at the ratio/formula feature (L9/F4261730), routes through L14 and L20, then to L25 and the logit. Path 2 is excitatory (weight=294.0) with just 2 hops from an embedding feature through L19 directly to the LOGIT. This dual-pathway structure -- one long mixed path from middle-layer domain features and one short excitatory path from embeddings -- explains the high confidence: both channels independently converge on " cat."

**[SYNTHESIS]** The puppy/kitten analogy produces the clearest mechanistic story for a non-geographic analogy. The "as" connector (F11438, L1) triggers analogy template recognition from the very first layer. The mathematical-proportion feature at Layer 9 (F4261730) implements the A:B::C:? ratio, and a direct 2-hop excitatory path from the embedding confirms the answer. The 75.6% confidence reflects convergent evidence: the life-stage relationship (puppy->dog, kitten->?) is unambiguous in the model's representation, and competing tokens are cleanly separated.""",

"""**[EARLY]** "Clock is to time as thermometer is to" activates an unusual set of early features. The top early node, F7856 at Layer 2 (node_id=2_7856_8, inf=0.8001), is labeled "the archaic word 'unto' and words immediately surrounding it" -- likely responding to the "is to" relational connector's archaic/formal character. F13575 at Layer 3 (node_id=3_13575_4, inf=0.7995) activates for "words that involve actions, especially verbs," registering the active relational nature of the measurement template. F7706 at Layer 0 (node_id=0_7706_4, inf=0.7993) fires for "the word 'pat' or relating to patents" -- likely detecting the technical/functional domain of clock and thermometer as measurement instruments.

**[MIDDLE]** Two remarkable middle-layer features appear: F13281 at Layer 13 (node_id=13_13281_8, inf=0.7982) activates for "words related to relationships between things" -- a direct representation of relational structure. More significantly, F12474 at Layer 15 (node_id=15_12474_5, inf=0.7964) is labeled "analogies in conversational text" -- the model has an explicit analogy-detection feature that fires in the middle layers for this prompt. This is the clearest evidence that the middle-layer circuit has learned a dedicated analogical reasoning sub-network.

**[LATE]** F14348 at Layer 20 (node_id=20_14348_8, inf=0.7999) activates for "words and conjunctions that connect other words" -- the connector/preposition feature seen in the Paris/Germany circuit. F3523 at Layer 24 (node_id=24_3523_8, inf=0.7997) fires for "language describing grammatical principles." F2469 at Layer 17 (node_id=17_2469_5, inf=0.7950) is labeled "analogies using 'the same way' construction" -- a second explicit analogy template feature in the late layers.

**[TOKEN COMPETITION]** " temperature" was predicted with 18.2% probability -- genuinely ambiguous, as "heat" and "warmth" are reasonable alternatives. The dominant path (Path 1, mixed, weight=523.2) travels 5 hops from L0 through L6, L17, L20-L25 to the logit. The presence of two explicit analogy features (F12474 at L15 and F2469 at L17) in the causal chain means this circuit is more self-aware of its analogical task than any other prompt in the dataset.

**[SYNTHESIS]** The Clock/thermometer analogy reveals the most explicit analogy-circuit activation in the dataset. The circuit contains dedicated analogy-detection features at Layer 15 ("analogies in conversational text") and Layer 17 ("analogies using 'the same way' construction"). Despite clear relational recognition, the prediction is uncertain (18.2%) because "thermometer" maps to multiple measurement concepts (temperature, heat, degrees). The circuit correctly solves the structural analogy but faces genuine semantic ambiguity in the final token-selection step.""",

"""**[EARLY]** "Book is to reading as radio is to" activates features in the activity/medium domain. The top early feature, F5683 at Layer 5 (node_id=5_5683_5, inf=0.7999), detects "technical terminology in scientific writing" -- likely responding to the formal register of the analogy template. F4328 at Layer 4 (node_id=4_4328_3, inf=0.7997) activates for "instances of how a goal may be achieved, or how someone plans to" -- encoding the functional/purposive relationship (books are for reading, radio is for listening). F663 at Layer 0 (node_id=0_663_4, inf=0.7995) fires for "words and phrases related to opinions, arguments, and discussion" -- potentially registering the communicative nature of both reading and listening.

**[MIDDLE]** F5517 at Layer 11 (node_id=11_5517_4, inf=0.8001) -- the highest-influence middle node -- is labeled "a wide array of words in a text," a broad feature detecting the general textual/linguistic nature of the prompt. F4175 at Layer 8 (node_id=8_4175_4, inf=0.7991) specifically fires for "mentions of published works, publishers, and literary studies" -- connecting the "book/reading" source domain. F2469 at Layer 17 (node_id=17_2469_8, inf=0.7961) fires for "analogies using 'the same way' construction" -- the analogy template detector also seen in the Clock/thermometer prompt.

**[LATE]** F22 at Layer 0 (node_id=0_22_7, inf=0.7984) fires for "words ending in '-ality' or 'other'" -- the abstract category placeholder. The analogy template feature (F2469) appearing in the late band at Layer 17 indicates that analogy recognition continues into the final prediction stages.

**[TOKEN COMPETITION]** " listening" was predicted with 34.5% probability. Path 1 is excitatory (weight=108.8, 2 hops): embedding -> L21 -> LOGIT -- the same short-circuit excitatory pattern seen in high-confidence predictions. The mixed Path 2 (weight=46.7) routes through L5 -> L11 -> L12 -> higher layers -> LOGIT, incorporating the "published works" feature (L8/F4175) into the causal chain.

**[SYNTHESIS]** The Book/radio analogy shows a functionally clean circuit: reading is the activity associated with books, listening with radio. The analogy template detector (F2469 at L17) fires for both this prompt and the Clock/thermometer one, suggesting a shared sub-circuit for activity/function analogies. The dominant mechanism is the 2-hop excitatory path from an embedding feature to L21 to LOGIT (Path 1, weight=108.8). The 34.5% confidence reflects genuine ambiguity between "listening," "broadcasting," and "hearing" -- all valid completions competing for the output slot.""",

"""**[EARLY]** "Leaf is to tree as petal is to" activates the richest set of botanical/natural features in the dataset. The top early node, F15463 at Layer 7 (node_id=7_15463_5, inf=0.8001), fires for "a multitude of concepts including things, exclamations, comparisons..." -- a broad analogy-context feature. Crucially, F6178 at Layer 6 (node_id=6_6178_4, inf=0.7999) detects "words related to domestic animals and farming," and F11868 at Layer 6 (node_id=6_11868_6, inf=0.7997) fires for "words related to animals and natural objects/phenomena" -- the model is encoding all prompt terms (leaf, tree, petal) as natural/biological objects from the earliest layers. This natural-objects cluster is the most domain-specific early activation in the dataset.

**[MIDDLE]** F8082 at Layer 10 (node_id=10_8082_8, inf=0.7986) activates for "language used to express complex dependencies" -- potentially encoding the part-whole relationship (leaf:tree = petal:flower). F1917 at Layer 11 (node_id=11_1917_4, inf=0.7978) fires for "abbreviations, measurements, units, and values," and F8179 at Layer 14 (node_id=14_8179_8, inf=0.7977) for "phrases with lots of function words (articles, prepositions, etc)" -- directly encoding the syntactic structure of the analogy template's relational connectors.

**[LATE]** F6647 at Layer 18 (node_id=18_6647_7, inf=0.7989) fires for "segments of code or legal documents" -- the formal-register structural feature that appears across many analogical prompts. F16267 at Layer 20 (node_id=20_16267_8, inf=0.7988) activates for "stream of consciousness writing, particularly related to..." -- an unexpected late-layer feature suggesting the model treats the open-ended analogy as a generative/creative task.

**[TOKEN COMPETITION]** " flower" was predicted with only 13.6% probability -- the second-lowest in the dataset. The dominant path (Path 1, mixed, weight=2086.9) has the highest total weight of any path in the entire dataset, driven by very large individual edge weights including a +74.6 edge at L21. Despite this extreme path weight, confidence is low because "flower" competes with "plant," "rose," and other botanical terms.

**[SYNTHESIS]** The Leaf/petal analogy is the most structurally striking circuit: it combines the strongest early domain-specific features (natural objects at L6) with the highest-weight causal path (2086.9) yet produces the second-lowest prediction confidence. This dissociation reveals that path weight is not a proxy for prediction confidence: the model has a rich botanical representation at early layers and a strong causal signal, but the signal spreads across many competing botanical tokens (flower, plant, bloom, blossom). The circuit correctly identifies the part-whole botanical relationship but cannot converge on a single answer token.""",

"""**[EARLY]** "Wheel is to car as wing is to" activates structural features from the very first layers. F3195 at Layer 2 (node_id=2_3195_6, inf=0.7998) detects "words related to shopping for apparel and gifts" -- likely responding to the relational/comparative structure. F2267 at Layer 5 (node_id=5_2267_4, inf=0.7995) fires for "law related terminology and references to specific cases" -- another formal-register structural feature. F1673 at Layer 5 (node_id=5_1673_5, inf=0.7991) activates for "the word 'general' and phrases containing 'as a whole'" -- capturing the generalizing/abstracting nature of the analogy frame.

**[MIDDLE]** Two directly relevant features appear. F13344 at Layer 9 (node_id=9_13344_3, inf=0.7987) is labeled "phrases suggesting uncertainty or comparison between two things" -- the recurring analogy-comparison feature. F14231 at Layer 9 (node_id=9_14231_8, inf=0.7978) activates for "words representing comparisons and relationships" -- a second explicit relational feature at the same layer. F2024 at Layer 8 (node_id=8_2024_6, inf=0.7996) fires for "terms related to clothes, fit, and fabrics" -- possibly encoding "wing" as a structural-fit component.

**[LATE]** The key late-layer discovery: F5563 at Layer 23 (node_id=23_5563_8, inf=0.7989) detects "words related to transport, aviation, and the military" -- a directly domain-specific feature that explicitly encodes the answer domain (aviation). This is the most domain-specific late-layer feature in any prompt. F6905 at Layer 18 (node_id=18_6905_8, inf=0.7993) fires for "code snippets, variable names, and programming keywords" -- the formal-register feature seen throughout.

**[TOKEN COMPETITION]** " airplane" was predicted with 16.2% probability -- competing with "bird," "plane," "aircraft," and "jet." Path 1 (mixed, weight=112.9) routes 5 hops from L2 through L7, L20, L22, L25 to the LOGIT. The aviation feature (F5563 at L23) sits in the region traversed by Path 2.

**[SYNTHESIS]** The Wheel/car/wing analogy has the clearest late-layer domain feature of any prompt: "transport, aviation, and the military" at Layer 23 (node_id=23_5563_8) directly encodes the answer domain. The circuit shows early structural parsing (L2-L5), middle-layer comparison features (L8-L9), then domain-specific convergence at Layer 23. The low confidence (16.2%) reveals that the aviation-domain feature competes against multiple valid aircraft-part-to-vehicle associations -- "airplane" wins over "bird" and "plane" by a narrow margin.""",

"""**[EARLY]** "Judge is to court as priest is to" activates institutional and procedural features at early layers. The top early node, F10535 at Layer 0 (node_id=0_10535_6, inf=0.8001), fires for "words related to medical procedures and studies" -- detecting formal professional-role terminology. F6863 at Layer 4 (node_id=4_6863_5, inf=0.7999) specifically activates for "instances of the word 'as' preceded by the word 'used' and/or followed by..." -- directly tracking the "is to...as" connective structure of the analogy. F5766 at Layer 5 (node_id=5_5766_5, inf=0.7997) fires for "scientific observations dealing with amount" -- possibly encoding the proportional structure of the analogy ratio.

**[MIDDLE]** F9756 at Layer 10 (node_id=10_9756_8, inf=0.7996) fires for "a variety of different concepts, including weather, being small..." -- encoding the relational abstraction of institutional roles. F6402 at Layer 9 (node_id=9_6402_8, inf=0.7994) activates for "references to laws, articles and sections" -- directly relevant to the "judge/court" source domain. Remarkably, F6505 at Layer 17 (node_id=17_6505_4, inf=0.7974) is labeled simply "court" -- the clearest single-concept feature in the entire dataset. This feature fires at Layer 17, explicitly encoding the source-domain institution and driving the analogical mapping to "church" as the priest's equivalent institution.

**[LATE]** F10549 at Layer 19 (node_id=19_10549_8, inf=0.7990) -- labeled "words and phrases related to religion and religious belief" -- is the decisive late-layer feature, firing just three layers before the logit. F14217 at Layer 20 (node_id=20_14217_8, inf=0.7985) activates for "text related to laws and government, and the path a law takes" -- connecting the legal source domain to the religious target.

**[TOKEN COMPETITION]** " church" was predicted with 48.6% probability -- the highest confidence among the non-geographic analogies. The dominant path (Path 1, mixed, weight=1951.5) goes from an embedding feature through L21 and L24 to the LOGIT. Path 2 (weight=70.3) begins at the religion feature (L19/F10549, node_id=19_10549_8) -- the "religion/religious belief" feature directly feeds the logit through L20->L21->L25->LOGIT. Path 3 (weight=14.9) begins at the recurring cross-graph feature F4828270 at Layer 7 (node_id=7_3099_2).

**[SYNTHESIS]** The Judge/court/priest/church analogy produces the cleanest institutional-role circuit. The model has dedicated single-concept features for the source ("court" at L17/F6505) and a domain feature for the target ("religion/religious belief" at L19/F55857145). The 48.6% confidence reflects competition from "temple," "parish," and "cathedral" -- but "church" wins as the most general institution at the same level of specificity as "court." The causal path through L19/F10549 ("religion/religious belief") -> L20 -> L21 -> L25 -> LOGIT is the clearest example of a domain-knowledge feature directly driving the final prediction.""",

"""**[EARLY]** "Soldier is to army as sailor is to" activates features related to institutional roles and formal factual structure. The top early node, F1931 at Layer 3 (node_id=3_1931_7, inf=0.7997), fires for "statements of fact linked to importance or findings" -- capturing the definitional, encyclopedic register of military taxonomy. F77 at Layer 0 (node_id=0_77_6, inf=0.7996) activates for "words related to medical, chemical or scientific terminology" -- a formal/categorical classification feature. F16175 at Layer 2 (node_id=2_16175_1, inf=0.7992) fires for "words related to medicine, including surgeries, anatomy, visual..." -- again a formal technical-category feature rather than a domain-specific one.

**[MIDDLE]** The most domain-specific feature appears in the middle layers: F2249 at Layer 13 (node_id=13_2249_8, inf=0.8001) activates for "noun phrases ending in '-ists', and also seems to have some other..." -- encoding the professional-role suffix pattern linking soldier/sailor as members of a category. The recurring cross-graph feature F4828270 at Layer 7 (node_id=7_3099_3, inf=0.7986) -- "a variety of reference codes, abbreviations, and identifiers" -- appears in the middle band, one of the 429 recurring analogy-circuit features from Step 5.

**[LATE]** The decisive late-layer feature is F15321 at Layer 16 (node_id=16_15321_8, inf=0.7999): "text related to military service and conscription" -- a domain-specific feature encoding the military branch taxonomy. This feature explicitly encodes the military domain at Layer 16, enabling the model to select "navy" as the branch of military service employing sailors (analogous to the army employing soldiers). F592 at Layer 23 (node_id=23_592_8, inf=0.7994) fires for "medical terminology related to studies, conditions, and treatments" -- a mismatched label reflecting co-activation with institutional service roles.

**[TOKEN COMPETITION]** " navy" was predicted with 21.4% probability. Unlike most other prompts, the circuit has very weak causal paths: Path 1 (mixed, weight=5.7) and Path 2 (excitatory, weight=4.2) are dramatically weaker than the 100+ weights seen in other prompts. This weak path signal, combined with the presence of two excitatory paths, suggests the model is operating with a diffuse, weakly-connected circuit for military taxonomy. Path 1 begins at F592 (Layer 23, "medical terminology"), routes to L24->L25->LOGIT -- a short convergent chain that bypasses most labeled features.

**[SYNTHESIS]** The Soldier/army/sailor/navy analogy produces the weakest circuit in the dataset, with path weights two orders of magnitude below those of the Leaf/petal and Judge/church prompts. Despite having a clear domain feature at Layer 16 (F15321: "military service and conscription"), the causal paths do not route through it -- the logit is primarily driven by short embedding-to-late-layer connections. This dissociation between the identified domain feature and the actual causal pathway suggests the "navy" prediction is partially driven by token co-occurrence statistics rather than a clean analogical inference chain. The 21.4% confidence reflects genuine competition from "fleet," "ship," and "naval" as alternative completions."""
]

for i, narrative in enumerate(narratives):
    if MARKER in content:
        replacement = f'**Mechanistic narrative:**\n\n{narrative}'
        content = content.replace(MARKER, replacement, 1)
        print(f'Replaced marker {i+1}/8')
    else:
        print(f'ERROR: marker not found for narrative {i+1}')
        break

remaining = content.count('[Claude Code')
print(f'Remaining markers: {remaining}')

with open('analogical_circuit_paper.md', 'w', encoding='utf-8') as f:
    f.write(content)
print('Paper saved.')
